name: tugasakhir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.1
  get_cli: ^1.8.1
  flutter_screenutil: ^5.9.0
  firebase_storage: ^11.7.4
  cached_network_image: ^3.3.1
  image_picker: ^1.1.1
  flutter_native_splash: ^2.4.0
  get_storage: ^2.1.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_fonts: ^6.2.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter



flutter: 
  assets: 
    - assets/
  uses-material-design: true

