// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDuFoDAp7qroquulsW995zgBToSsL8I0k',
    appId: '1:998970867183:web:dd7a0c3a3f64b062a14a1a',
    messagingSenderId: '998970867183',
    projectId: 'tugasakhir-928d4',
    authDomain: 'tugasakhir-928d4.firebaseapp.com',
    storageBucket: 'tugasakhir-928d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTyZqT7HFLnT5AmKSwK70maEdmlCf7MdM',
    appId: '1:998970867183:android:cdac622f2aad2baaa14a1a',
    messagingSenderId: '998970867183',
    projectId: 'tugasakhir-928d4',
    storageBucket: 'tugasakhir-928d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAfzkDzLt7ufR2I3ZuOPJaleUwbxv9WCM',
    appId: '1:998970867183:ios:e477913340d335b4a14a1a',
    messagingSenderId: '998970867183',
    projectId: 'tugasakhir-928d4',
    storageBucket: 'tugasakhir-928d4.appspot.com',
    iosBundleId: 'com.example.tugasakhir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAfzkDzLt7ufR2I3ZuOPJaleUwbxv9WCM',
    appId: '1:998970867183:ios:e477913340d335b4a14a1a',
    messagingSenderId: '998970867183',
    projectId: 'tugasakhir-928d4',
    storageBucket: 'tugasakhir-928d4.appspot.com',
    iosBundleId: 'com.example.tugasakhir',
  );

}